### ISSUE TITLE
Name in Modulefile is incorrect

### ISSUE THREAD

**Issue by razorsedge** [gini/puppet-virtualbox#4]
The name of this module should be "virtualbox" since the class name is `class virtualbox`. Please update file `Modulefile` `name 'puppet-virtualbox'` to be `name 'virtualbox'`.

**Comment by joschi** [comment]
According to http://docs.puppetlabs.com/puppet/3/reference/modules_publishing.html#write-a-modulefile the `name` property should be `smarchive-virtualbox` but not just `virtualbox`.

**Comment by razorsedge** [comment]
Doh!  You'd think I would know better. :-)

**Comment by razorsedge** [comment]
Might as well also fix the `dependency   'puppetlabs/apt', '>= 1.0'` to be `dependency   'puppetlabs/apt', '>=1.0.0'`.

**Comment by joschi** [comment]
The dependency version for puppetlabs/apt had already been fixed in #3.
