### ISSUE TITLE
Update Forge with new version

### ISSUE THREAD

**Issue by sherzberg** [gini/puppet-virtualbox#7]
The current version on the forge doesn't seem to like the apt dependency version format. Can you upload a new version based on the current code?

**Comment by joschi** [comment]
Thanks for the bug report!

Could you please add the error messages you're receiving when using this module in order to diagnose the problem?

**Comment by sherzberg** [comment]
The current version out on the Forge has this for a dependency:

dependency   'puppetlabs/apt', '>= 1.0'

And here is the error I get when I try to use it:

[localhost] out: Error: undefined method `MIN' for SemVer:Class
[localhost] out: Error: Try 'puppet help module install' for usage
[localhost] out: Error executing puppet module install:
[localhost] out: puppet module install --target-dir '/etc/puppet/.tmp/librarian/cache/source/puppet/forge/3792e516e3ff92a0ef9f5e827f8e76eb/smarchive/virtualbox/version/96a5d0f2a178420f4134741cf92b684c' --modulepath '/etc/puppet/.tmp/librarian/cache/source/puppet/forge/3792e516e3ff92a0ef9f5e827f8e76eb/smarchive/virtualbox/version/96a5d0f2a178420f4134741cf92b684c' --ignore-dependencies 'smarchive/virtualbox'

The current code has this as a dependency and it works fine:

dependency 'puppetlabs/apt', '>= 1.0.0'

**Comment by joschi** [comment]
The issue has been fixed in [version 0.2.3](http://forge.puppetlabs.com/smarchive/virtualbox/0.2.3) of the module.

Thanks again for opening the issue! :+1:
