### ISSUE TITLE
yumrepo needs $descr parameter

### ISSUE THREAD

**Issue by razorsedge** [gini/puppet-virtualbox#8]
In Class['virtualbox::repo::redhat'], yumrepo needs $descr parameter to keep the following warning from appearing on each manual yum invocation:

```
Repository 'virtualbox' is missing name in configuration, using id
```

Something like `descr => 'Oracle VirtualBox'` should suffice or copy from http://download.virtualbox.org/virtualbox/rpm/el/virtualbox.repo.

**Comment by joschi** [comment]
Thanks for your bug report. I just released [gini/virtualbox 0.2.4](http://forge.puppetlabs.com/gini/virtualbox/0.2.4) on the Forge with a fix for the problem.
